apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "neunn/dockerCephfsVolumePlug"
      options:
        monitors: "127.0.0.1"
        path: "/aaa"
        secretFile: "/etc/ceph/ceph.client.admin.keyring"
